app:
  name: "Unbound Future Admin"
  env: "development"
  host: "0.0.0.0"
  port: 8000

database:
  url: "postgresql://unbound_future:Unbound_future618@172.19.0.12:5432/unbound_future_db"

feishu:
  app_id: "cli_a9b795eee2799cbd"
  app_secret: "kRjygCLAlUZ4YiC0oCS7lhOWaFKeUSU1"
  redirect_uri: "http://43.135.37.109:5173/auth/callback"

security:
  jwt_secret: "unbound_future_admin"
  jwt_algorithm: "HS256"
  access_token_expire_minutes: 1200

worker:
  max_threads: 512

storage:
  transfer_service_url: "http://r2-worker.xinglong940713.workers.dev/initiate-copy"
  src:
    endpoint: "https://6d18700b4bd3fff2b330035c35b0bbeb.r2.cloudflarestorage.com/tmp-transfer2"
    access_key: "6e17dce5e6699ec405f7ec07deecf321"
    secret_key: "4916026eb627351979f06b898b4f8f67137caba46c39bab83934eb29a97f92ad"
    region: "auto"
