FROM node:18-alpine
COPY frontend/ /app/frontend/
WORKDIR /app/frontend/
RUN rm -f package-lock.json
RUN npm config set registry https://registry.npmmirror.com
RUN npm install
RUN npm run build

FROM nginx:1.19-alpine
COPY --from=0 /app/frontend/dist/ /usr/share/nginx/html/