apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: unbound-future
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
      - name: unbound-registry-secret
      containers:
      - name: frontend
        image: image.unboundfuture.ai/unbound-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: unbound-future
  labels:
    service.cloud.tencent.com/loadbalance-type: OPEN
  annotations:
    service.kubernetes.io/service.extensiveParameters: '{"AddressIPVersion":"IPV4","InternetAccessible":{"InternetChargeType":"TRAFFIC_POSTPAID_BY_HOUR","InternetMaxBandwidthOut":10}}'
spec:
  selector:
    app: frontend
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: callback
    protocol: TCP
    port: 3000
    targetPort: 80
  type: LoadBalancer